name: Remove ECR Repository

on:
  workflow_dispatch

env:
  ECR_REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_PRIVATE_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_PRIVATE_SECRET_KEY }}
        aws-region: ap-northeast-2
        
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Delete ECR repository
      run: aws ecr delete-repository --repository-name $ECR_REPOSITORY --force
    
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: ECR Purge Notification
        fields: repo
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
